[package]
name = "dfm-version"
version = "704.0.1"
authors = ["Dara Keon <lc.sales.duarte@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "4.0.0"
git2 = "0.13.25"
regex = "1.5.4"
reqwest = { version = "0.11.9", features = ["blocking"] }
json = "0.12.4"
