  test_midna:
    docker:
      - image: python:3.11 # if change, remember to change save_cache
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - python-{{ checksum "midna/src/requirements.txt" }}
      - run:
          path: midna
          name: run tests
          command: |
            set -o allexport
            source example.env
            set +o allexport
            cd src
            python manage.py test deleted_users

